import type { Metadata } from "next";
import BaseHeader from "../components/BaseHeader";
import "./globals.css";

export const metadata: Metadata = {
  title: "todo Vercel Pg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <BaseHeader title="vercel Postgres Todo" />
        {children}
      </body>
    </html>
  );
}
